
#    - id: check-yaml
#    - id: check-added-large-files
#    - id: trailin-gwhitespace

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.9
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format
